import { CatalogItem, UniqueAdvantageCatalogItem } from './catalog-types';

export const alphaAdvantages: CatalogItem[] = [
  { name: "Aceleração", cost: "1 ponto", description: "Permite múltiplos movimentos por turno e bônus de velocidade." },
  { name: "Adaptador", cost: "1 ponto", description: "Permite alterar o tipo de dano do ataque (Físico ou Energia) sem penalidade." },
  { name: "Aliado", cost: "1 ponto (cada)", description: "Um companheiro de Nível de 1 a 5." },
  { name: "Alquimista", cost: "1 ponto", description: "Permite criar itens, reduzindo o custo em PM de rituais pela metade." },
  { name: "Aparência Inofensiva", cost: "1 ponto", description: "Surpreende o oponente no 1º turno; bônus de +1 em testes de H para Manipulação." },
  { name: "Arcano", cost: "4 pontos", description: "Acesso total às Magias Branca, Elemental e Negra, reduzindo 1 PM no custo." },
  { name: "Área de Batalha", cost: "2 pontos", description: "Transporta o combate para uma dimensão. Efeitos à escolha: H+1 e A+2, ou F/PdF+2 e A+2, ou Ataques Especiais sem custo em PMs." },
  {
    name: "Arena",
    cost: "1 ponto",
    description: "Recebe H+2 em um tipo de terreno específico. Escolha o seu terreno. Para comprar Arenas extras, você precisa recomprar a vantagem.",
    isModular: true,
    baseCostPt: 0,
    modifiers: [
      { id: "are_agua", name: "Água", costPt: 1, description: "Praias, barcos, chuva, superfícies aquáticas ou submerso" },
      { id: "are_ceu", name: "Céu", costPt: 1, description: "Combate aéreo (quando ambos voam)" },
      { id: "are_estereis", name: "Ermos", costPt: 1, description: "Desertos, montanhas, geleiras, planícies" },
      { id: "are_urbanas", name: "Cidades", costPt: 1, description: "Ruas, telhados, prédios, aposentos" },
      { id: "are_subterraneos", name: "Subterrâneos", costPt: 1, description: "Cavernas, masmorras, esgotos" },
      { id: "are_outro", name: "Um único lugar", costPt: 1, description: "Um local específico definido com o Mestre" }
    ]
  },
  {
    name: "Armadura Extra",
    cost: "Especial",
    description: "Dobra a Armadura (A) contra o(s) tipo(s) de dano escolhido(s). Energias: 1PT | Físicos: 2PT | Gerais: 3PT.",
    isModular: true,
    baseCostPt: 0,
    modifiers: [
      { id: "arm_fogo", name: "Fogo", costPt: 1, description: "Dano de Fogo" },
      { id: "arm_frio", name: "Frio", costPt: 1, description: "Dano de Frio" },
      { id: "arm_eletrico", name: "Elétrico", costPt: 1, description: "Dano Elétrico" },
      { id: "arm_quimico", name: "Químico", costPt: 1, description: "Dano Químico" },
      { id: "arm_sonico", name: "Sônico", costPt: 1, description: "Dano Sônico" },
      { id: "arm_corte", name: "Corte", costPt: 2, description: "Dano por Corte" },
      { id: "arm_perfuracao", name: "Perfuração", costPt: 2, description: "Dano por Perfuração" },
      { id: "arm_esmagamento", name: "Esmagamento", costPt: 2, description: "Dano por Esmagamento" },
      { id: "arm_magia", name: "Magia", costPt: 3, description: "Qualquer dano causado por magia" },
      { id: "arm_forca", name: "Força", costPt: 3, description: "Ataques corporais focados em Força" },
      { id: "arm_pdf", name: "Poder de Fogo", costPt: 3, description: "Ataques à distância baseados em PdF" }
    ]
  },
  {
    name: "Ataque Especial",
    cost: "1+ pontos",
    description: "Ataque elemental ou especial. Custo base: 1PT + modificadores escolhidos.",
    isModular: true,
    baseCostPt: 1,
    modifiers: [
      { id: "ae_amplo", name: "Amplo", costPt: 2, description: "Atinge todos os alvos no alcance do ataque (+2 PMs)" },
      { id: "ae_lento", name: "Lento", costPt: -1, description: "Apenas para ataques com PdF. Alvo recebe H+2 na esquiva" },
      { id: "ae_paralisante", name: "Paralisante", costPt: 1, description: "Além de dano, funciona como Vantagem Paralisia (+1 PM)" },
      { id: "ae_penetrante", name: "Penetrante", costPt: 1, description: "Impõe A-2 contra o alvo na sua Força de Defesa (+1 PM)" },
      { id: "ae_perigoso", name: "Perigoso", costPt: 1, description: "Acerto crítico com resultado 5 ou 6 no dado (+1 PM)" },
      { id: "ae_perto_morte", name: "Perto da Morte", costPt: -2, description: "O ataque só pode ser usado quando você está Perto da Morte (-1 PM)" },
      { id: "ae_poderoso", name: "Poderoso", costPt: 1, description: "Em caso de crítico, o ataque triplica sua F ou PdF (+1 PM)" },
      { id: "ae_preciso", name: "Preciso", costPt: 1, description: "Impõe H-2 contra o alvo em sua Força de Defesa" },
      { id: "ae_teleguiado", name: "Teleguiado", costPt: 1, description: "Apenas para PdF. Ataque persegue impondo H-2 in esquivas" }
    ]
  },
  { name: "Ataque Múltiplo", cost: "1 ponto", description: "Permite fazer mais ataques corpo-a-corpo no turno. Cada ataque extra (além do primeiro) custa 1 PM." },
  { name: "Boa Fama", cost: "1 ponto", description: "Você é respeitado e famoso. Pode ser mais difícil passar despercebido ou agir disfarçado." },
  { name: "Clericato", cost: "1 ponto", description: "Acesso a Magia Branca (e outras definidas pelo mestre), com 3 magias extras iniciais." },
  { name: "Deflexão", cost: "1 ponto", description: "2 PMs para duplicar a H na FD contra ataques de PdF." },
  { name: "Elementalista", cost: "1 ponto (cada)", description: "Reduz custo de PM pela metade (arredondado para cima) em magias de um elemento." },
  { name: "Energia Extra", cost: "1 ou 2 pontos", description: "Gasta 2 PMs para recuperar todos os PVs. 1 pt: Só funciona Perto da Morte. 2 pts: Qualquer momento." },
  { name: "Energia Vital", cost: "2 pontos", description: "Gasta PVs em lugar de PMs (2 PVs = 1 PM). Apenas para magias e vantagens." },
  { name: "Familiar", cost: "1 ponto", description: "Pequeno animal mágico que partilha Habilidades e Vantagens, com Ligação Natural." },
  { name: "Forma Alternativa", cost: "2 pontos (cada)", description: "Transforma-se em outra forma com ficha própria. Demora um movimento." },
  { name: "Genialidade", cost: "1 ponto", description: "Recebe H+2 para usar ou aprender Perícias, ou testes envolvendo perícias que não possua." },
  { name: "Imortal", cost: "1 ou 2 pontos", description: "1pt: Retorna da morte após dias/meses. 2pts: Retorna após o combate." },
  { name: "Inimigo", cost: "1 ponto (cada)", description: "H+2 em combate e em testes de perícias envolvendo um grupo de criaturas específico." },
  { name: "Invisibilidade", cost: "2 pontos", description: "Fora de combate reduz testes de furtividade. Em combate impõe H-1 (C/C) ou H-3 (Longa). 1 PM/turno." },
  { name: "Invulnerabilidade", cost: "Especial", description: "Dano de um tipo específico é dividido por dez. Só pode ser obtida em campanha/única." },
  { name: "Ligação Natural", cost: "1 ponto", description: "Conexão especial com Aliado. Comunicação telepática visual; sentir emoções cegas." },
  { name: "Magia Branca", cost: "2 pontos", description: "Acesso às Magias de cura ou defensivas." },
  { name: "Magia Elemental", cost: "2 pontos", description: "Acesso às Magias baseadas nos quatro elementos." },
  { name: "Magia Negra", cost: "2 pontos", description: "Acesso às Magias ligadas a morte e deterioração." },
  { name: "Magia Irresistível", cost: "1 a 3 pontos", description: "Impõe redutor no teste de Resistência da vítima às magias. 1pt(-1), 2pts(-2), 3pts(-3)." },
  { name: "Membros Elásticos", cost: "1 ponto", description: "Permite realizar ataques corporais normais a distância como se tivesse alcance de PdF." },
  { name: "Membros Extras", cost: "1 ponto (cada)", description: "Permite um ataque extra ou bloqueio de FD+1 constante. Acumula os efeitos de Monstruoso." },
  { name: "Memória Expandida", cost: "2 pontos", description: "Memória infalível. Aprende perícias ao observar (-1 perícia por vez). Não precisa testar aprender magias." },
  { name: "Mentor", cost: "1 ponto", description: "Um mestre que fornece três magias extras, e responde a perguntas ou dá dicas telepaticamente." },
  { name: "Paladino", cost: "1 ponto", description: "Guerreiro do bem. R+1 para PVs e PMs. Pode conjurar Cura Mágica e Detectar o Mal pelo custo normal em PMs." },
  { name: "Paralisia", cost: "1 ponto", description: "2 PMs ou mais. Se causar dano, o alvo deve passar em teste de R ou ficar paralisado por (PMs gastos/2) turnos." },
  { name: "Parceiro", cost: "1 ponto (cada)", description: "Agem como um só lutador, combinando características mais altas. Dano recebido é dividido igualmente." },
  { name: "Patrono", cost: "1 ponto", description: "Grande organização. 1 PM invoca ajuda de acordo com a situação. Para magos, concede três magias extras." },
  { name: "Poder Oculto", cost: "1 ponto", description: "Gasta 1 PM para aumentar uma característica em +1 (max +5, 1 turno/pto), ou todas (+2, max +10). Perde se atacado/atingir 0 PVs." },
  { name: "Pontos de Magia Extras", cost: "1 ponto (cada)", description: "Soma R+2 no cálculo de PMs totais (não na Resistência real)." },
  { name: "Pontos de Vida Extras", cost: "1 ponto (cada)", description: "Soma R+2 no cálculo de PVs totais (não na Resistência real)." },
  { name: "Possessão", cost: "2 pontos", description: "Possui um corpo desacordado. Gasta PM igual à R do alvo ao entrar e a cada hora." },
  { name: "Reflexão", cost: "2 pontos", description: "Gasta 2 PMs para duplicar H na FD e, se FD >= FA, devolve o ataque de PdF com a FA original." },
  { name: "Regeneração", cost: "3 pontos", description: "Recupera 1 PV por turno. Altera resultados de testes de Morte (recupera PV mais rápido). Não afeta PMs." },
  { name: "Resistência à Magia", cost: "1 ponto", description: "Concede +2 no teste de R para ignorar efeito de vantagem ou magia (exceto dano verdadeiro)." },
  { name: "Riqueza", cost: "2 pontos", description: "Gasta 1 PM para ter ajuda como o dinheiro permitir. Nunca substitui Vantagens/Desvantagens." },
  {
    name: "Sentidos Especiais",
    cost: "1-2 pontos",
    description: "1 ponto: 3 sentidos à sua escolha. 2 pontos: todos os sentidos disponíveis na lista.",
    isModular: true,
    baseCostPt: 0,
    modifiers: [
      { id: "se_audicao", name: "Audição Aguçada", costPt: 0, description: "Ouvir sons muito baixos ou distantes." },
      { id: "se_faro", name: "Faro Aguçado", costPt: 0, description: "Farejar como um perdigueiro." },
      { id: "se_infra", name: "Infravisão", costPt: 0, description: "Ver calor; fácil ver no escuro." },
      { id: "se_radar", name: "Radar", costPt: 0, description: "Perceber formas ao redor mesmo de olhos fechados." },
      { id: "se_invisivel", name: "Ver o Invisível", costPt: 0, description: "Ver coisas e seres invisíveis." },
      { id: "se_visao_aguc", name: "Visão Aguçada", costPt: 0, description: "Enxergar mais longe." },
      { id: "se_raiosx", name: "Visão de Raio X", costPt: 0, description: "Ver através de portas e paredes (exceto chumbo/mágicos)." }
    ]
  },
  { name: "Separação", cost: "2 pontos", description: "Gasta 4 PMs para invocar cópias exatas de si (máximo = Resistência). As cópias sofrem penalidade de -1 nas características." },
  { name: "Telepatia", cost: "1 ponto", description: "2 PMs por uso: Lê pensamentos (H+2 Investigação/Lábia), Analisa poder, Revela tesouro, ou Prevê movimentos adversários (+1 Iniciativa/Esquiva)." },
  { name: "Teleporte", cost: "2 pontos", description: "Gasta 1 PM para se teleportar para local visível (até 10m x Habilidade). Funciona como mover-se." },
  { name: "Tiro Carregável", cost: "1 ponto", description: "Gasta 2 PMs e um turno inteiro concentrando para dobrar o PdF no ataque do turno seguinte. Fica indefeso durante concentração." },
  { name: "Tiro Múltiplo", cost: "2 pontos", description: "Vários ataques de PdF em uma rodada. Cada disparo (incluindo o primeiro) consome 1 PM. Máximo de ataques = Habilidade." },
  { name: "Toque de Energia", cost: "1 ponto (cada)", description: "Transmitir energia com FA = A + 1d para cada PM gasto. Máximo PMs igual à Armadura. Ignora Habilidade na FA." },
  { name: "Torcida", cost: "1 ponto", description: "Se o público for a favor, ganha H+1 e impõe H-1 ao oponente (se ele falhar em teste de R)." },
  { name: "Voo", cost: "2 pontos", description: "Permite voar. H1: levitar; H2: 20m/s; H3+: 40m/s, +40m/s por ponto de H extra." },
  { name: "Xamã", cost: "1 ponto", description: "Forte ligação com o mundo dos espíritos. Pode interagir e atacar seres incorpóreos. Recebe Ver o Invisível para esse fim." }
];

export const alphaDisadvantages: CatalogItem[] = [
  { name: "Ambiente Especial", cost: "-1 ponto", description: "Fora do ambiente nativo (após R dias), perde 1 Força e 1 Resistência por dia. Recupera com 24h no ambiente." },
  { name: "Assombrado", cost: "-1 ou -2 pontos", description: "Atormentado por assombração. Role 1d6 no combate: 4, 5 ou 6 = -1 em FA e FD (-1pt) ou redutor em todas as Características (-2pts)." },
  { name: "Bateria", cost: "-1 ponto", description: "Reserva de energia: 2 horas por ponto de R. Depois perde 1 Força e 1 Resistência por hora até 'desligar'." },
  {
    name: "Código de Honra",
    cost: "-1 ponto (cada)",
    description: "Princípios rígidos de conduta. Violar um Código custa 1 PD.",
    isModular: true,
    baseCostPt: 0,
    modifiers: [
      { id: "co_asimov1", name: "1ª Lei de Asimov", costPt: -1, description: "Jamais causar mal a um ser humano, ou permitir que sofra mal" },
      { id: "co_asimov2", name: "2ª Lei de Asimov", costPt: -1, description: "Sempre obedecer ordens de humanos, exceto quando violam outros códigos" },
      { id: "co_combate", name: "Combate", costPt: -1, description: "Nunca atacar oponentes indefesos ou em desvantagem numérica" },
      { id: "co_cacador", name: "Caçador", costPt: -1, description: "Nunca matar/capturar fêmeas grávidas/filhotes; nunca abandonar caça" },
      { id: "co_cavalheiro", name: "Cavalheiro", costPt: -1, description: "Nunca atacar mulheres; sempre atender pedido de ajuda de uma mulher" },
      { id: "co_derrota", name: "Derrota", costPt: -1, description: "Nunca aceitar derrota; deve lutar até 0 PVs e se matar se capturado" },
      { id: "co_desafio", name: "Desafio", costPt: -1, description: "Jamais recusar desafios. Cumprir punições. Priorizar desafios individuais" },
      { id: "co_gratidao", name: "Gratidão", costPt: -1, description: "Se for salvo, deve servir o salvador até devolver o favor" },
      { id: "co_herois", name: "Heróis", costPt: -1, description: "Sempre cumprir palavras, proteger quem precisa, nunca recusar pedido de ajuda" },
      { id: "co_honestidade", name: "Honestidade", costPt: -1, description: "Nunca roubar, trapacear, mentir, desobedecer a leis" },
      { id: "co_redencao", name: "Redenção", costPt: -1, description: "Jamais atacar sem provocação; sempre aceitar rendição" }
    ]
  },
  {
    name: "Deficiência Física",
    cost: "-1 a -3 pontos",
    description: "Limitação física ou sensorial. Escolha a debilitação e sua gravidade.",
    isModular: true,
    baseCostPt: 0,
    modifiers: [
      { id: "db_audicao", name: "Audição Ruim", costPt: -1, description: "-1 para notar inimigos escondidos" },
      { id: "db_cego", name: "Cego", costPt: -2, description: "-1 ataques corpo-a-corpo, -3 longa distância e esquivas" },
      { id: "db_mudo", name: "Mudo", costPt: -1, description: "Incapaz de falar; não conjura magias faladas; testes sociais difíceis" },
      { id: "db_surdo", name: "Surdo", costPt: -1, description: "-1 para notar inimigos. Não ouve aproximantes." },
      { id: "db_semfaro", name: "Sem Faro", costPt: 0, description: "Não sente cheiro nem gosto" },
      { id: "db_visao", name: "Visão Ruim", costPt: -1, description: "Míope ou caolho; -1 para esquivas e à distância; -1 para inimigos escondidos" }
    ]
  },
  { name: "Dependência", cost: "-2 pontos", description: "Precisa consumir ou fazer algo diariamente. Se não fizer, -1 R (ou -1 Habilidade)." },
  { name: "Devoção", cost: "-1 ponto", description: "Dedicado a um dever sagrado ou missão. Sem poder persegui-la, tem -1 em todas as características." },
  { name: "Fetiche", cost: "-1 ponto", description: "Precisa de um objeto para canalizar poderes ou magia. Se perder não usa magia." },
  { name: "Fúria", cost: "-1 ponto", description: "Sempre que sofrer dano, testa R. Se falhar ataca a fonte incansavelmente e não usa PMs." },
  { name: "Inculto", cost: "-1 ponto", description: "Dificuldades de comunicação verbal. Outros têm muita dificuldade em fazê-lo conversar." },
  {
    name: "Insano",
    cost: "0 a -3 pontos",
    description: "Distúrbio mental. Apenas personagens com Aliado/Patrono/etc continuam confiando em você.",
    isModular: true,
    baseCostPt: 0,
    modifiers: [
      { id: "ins_distraido", name: "Distraído", costPt: 0, description: "-1 naquilo que não quer fazer" },
      { id: "ins_dupla", name: "Dupla Personalidade", costPt: 0, description: "Duas fichas idênticas que mudam em perigo" },
      { id: "ins_clepto", name: "Cleptomaníaco", costPt: -1, description: "Rouba por ser interessante. R para evitar." },
      { id: "ins_compulsivo", name: "Compulsivo", costPt: -1, description: "Ação diária > 1h para satisfazer" },
      { id: "ins_demente", name: "Demente", costPt: -1, description: "Igual Inculto" },
      { id: "ins_fantasia", name: "Fantasia", costPt: -1, description: "Acredita ser algo que não é" },
      { id: "ins_fobia_1pt", name: "Fobia (-1 pt)", costPt: -1, description: "Medo incomum. Encontro 25% das vezes" },
      { id: "ins_furia", name: "Fúria", costPt: -1, description: "Igual à desvantagem" },
      { id: "ins_depressivo", name: "Depressivo", costPt: -2, description: "Igual a Assombrado" },
      { id: "ins_fobia_2pts", name: "Fobia (-2 pts)", costPt: -2, description: "Medo comum. Encontro 50% das vezes" },
      { id: "ins_histerico", name: "Histérico", costPt: -2, description: "Igual a Assombrado" },
      { id: "ins_homicida", name: "Homicida", costPt: -2, description: "Precisa matar humanoide/humano a cada 1d dias" },
      { id: "ins_megalomaniaco", name: "Megalomaníaco", costPt: -1, description: "Acredita ser invencível; nunca recusa desafio ou foge" },
      { id: "ins_mentiroso", name: "Mentiroso", costPt: -1, description: "Nunca diz a verdade" },
      { id: "ins_obsessivo", name: "Obsessivo", costPt: -1, description: "Igual a Devoção" },
      { id: "ins_paranoico", name: "Paranoico", costPt: -1, description: "Não confia em ninguém. Não dorme direito." },
      { id: "ins_sonambulo", name: "Sonâmbulo", costPt: 0, description: "Anda dormindo. Acorda ao sofrer dano" },
      { id: "ins_suicida", name: "Suicida", costPt: 0, description: "Não dá valor à vida, busca se suicidar" },
      { id: "ins_fobia_3pts", name: "Fobia (-3 pts)", costPt: -3, description: "Medo diário. Quase o tempo todo" }
    ]
  },
  { name: "Interferência", cost: "0 pontos", description: "Emite campo constante que atrapalha comunicação rádio e certos aparelhos." },
  { name: "Interferência Mágica", cost: "0 pontos", description: "Aura antimágica a até 10m. Se rodar 1 ou 2 no dado a magia falha." },
  { name: "Má Fama", cost: "-1 ponto", description: "Infame. Todos desconfiam de você, e você é logo acusado quando há suspeitos." },
  {
    name: "Maldição",
    cost: "-1 a -2 pontos",
    description: "Uma sina perturbadora diária.",
    isModular: true,
    baseCostPt: 0,
    modifiers: [
      { id: "mal_suave", name: "Suave (-1 pt)", costPt: -1, description: "Irritante mas não causa penalidade" },
      { id: "mal_grave", name: "Grave (-2 pts)", costPt: -2, description: "Coloca a vida em risco" }
    ]
  },
  { name: "Modelo Especial", cost: "-1 ponto", description: "Corpo diferente do padrão humanoide. Não pode usar equipamentos normais." },
  { name: "Monstruoso", cost: "-1 ponto", description: "Aparência repulsiva e assustadora. Causa pânico." },
  { name: "Munição Limitada", cost: "-1 ponto", description: "Pode atirar apenas 3 vezes seu valor de Poder de Fogo antes de precisar recarregar." },
  {
    name: "Poder Vergonhoso",
    cost: "0 a -1 ponto",
    description: "Algo estranho ou embaraçoso acontece ao usar poderes que custem PMs.",
    isModular: true,
    baseCostPt: 0,
    modifiers: [
      { id: "pv_agradavel", name: "Agradável (-1 pt)", costPt: -1, description: "Ilusões bonitas não afetam mechas. Alvo ganha A+1 e R+1 para resistir" },
      { id: "pv_constrange", name: "Constrangedor (-1 pt)", costPt: -1, description: "Atos vergonhosos, danças, magias com FA-1" },
      { id: "pv_exagerado", name: "Exagerado (-1 pt)", costPt: -1, description: "Efeitos fantásticos e música alta." },
      { id: "pv_hentai", name: "Hentai (0 pts)", costPt: 0, description: "Roupas da vítima ficam transparentes ou somem temporariamente." }
    ]
  },
  { name: "Poder Vingativo", cost: "-1 ponto", description: "Toda magia ou poder que consuma PMs causa 1 ponto de dano direto a você." },
  { name: "Ponto Fraco", cost: "-1 ponto", description: "Fraqueza tática. Inimigo que descobrir ganha H+1 contra você." },
  { name: "Protegido Indefeso", cost: "-1 ponto (cada)", description: "Deve proteger alguém com a vida. Penalidades se protegido em perigo." },
  {
    name: "Restrição de Poder",
    cost: "-1 a -3 pontos",
    description: "Em certa condição, usa 2x PMs nas magias e vantagens.",
    isModular: true,
    baseCostPt: 0,
    modifiers: [
      { id: "rp_incomum", name: "Incomum (-1 pt)", costPt: -1, description: "Condição rara (25% do tempo, ex: molhado)" },
      { id: "rp_comum", name: "Comum (-2 pts)", costPt: -2, description: "Condição comum (50% do tempo, ex: durante dia/noite)" },
      { id: "rp_muito", name: "Muito Comum (-3 pts)", costPt: -3, description: "Quase sempre" }
    ]
  },
  {
    name: "Vulnerabilidade",
    cost: "Especial",
    description: "Não dá pontos nem é escolhida no começo. Reduz A a zero para calcular FD na vulnerabilidade.",
    isModular: true,
    baseCostPt: 0,
    modifiers: [
      { id: "vul_acido", name: "Químico / Ácido", costPt: 0, description: "Vulnerável a Ácido/Químicos" },
      { id: "vul_eletrico", name: "Elétrico", costPt: 0, description: "Vulnerável Elétrico" },
      { id: "vul_fogo", name: "Fogo/Calor", costPt: 0, description: "Vulnerável a Fogo" },
      { id: "vul_frio", name: "Frio/Gelo", costPt: 0, description: "Vulnerável a Frio" },
      { id: "vul_luz", name: "Luz", costPt: 0, description: "Vulnerável a Luz" },
      { id: "vul_sonico", name: "Sônico", costPt: 0, description: "Vulnerável Sônico" },
      { id: "vul_trevas", name: "Trevas", costPt: 0, description: "Vulnerável Trevas" },
      { id: "vul_magia", name: "Magia", costPt: 0, description: "Vulnerável a Magia" },
      { id: "vul_corte", name: "Corte", costPt: 0, description: "Vulnerável Lacerante" },
      { id: "vul_esmag", name: "Esmagamento", costPt: 0, description: "Vulnerável Contusão" },
      { id: "vul_perfuracao", name: "Perfuração", costPt: 0, description: "Vulnerável Perfuração" }
    ]
  }
];

export const alphaSkills: CatalogItem[] = [
  { name: "Animais", cost: "2 pontos", description: "Permite cuidar, tratar ferimentos, domar animais selvagens e treiná-los." },
  { name: "Arte", cost: "2 pontos", description: "Sensibilidade e talento para artes. Inclui Atuação, Falsificação, Instrumentos, etc." },
  { name: "Ciência", cost: "2 pontos", description: "Ciências em geral, incluindo Astronomia, Biologia, Geografia, História, etc." },
  { name: "Crime", cost: "2 pontos", description: "Conhecimentos de espião ou falsário. Inclui Armadilhas, Arrombamento, Furtividade, Punga." },
  { name: "Esporte", cost: "2 pontos", description: "Prática de esportes diversos. Inclui Acrobacia, Alpinismo, Arquearia, Natação, etc." },
  { name: "Idiomas", cost: "2 pontos", description: "Poliglota. Cada língua conta como uma especialização." },
  { name: "Investigação", cost: "2 pontos", description: "Técnicas policiais ou de agente secreto. Inclui Disfarce, Rastreio, Interrogatório." },
  { name: "Máquinas", cost: "2 pontos", description: "Habilidade com máquinas, veículos e computadores. Inclui Mecânica e Computação." },
  { name: "Manipulação", cost: "2 pontos", description: "Obter favores através de truques. Inclui Lábia, Sedução, Hipnose." },
  { name: "Medicina", cost: "2 pontos", description: "Saber diagnosticar e curar doenças. Inclui Primeiros Socorros, Cirurgia." },
  { name: "Sobrevivência", cost: "2 pontos", description: "Sobreviver em lugares selvagens. Inclui Pesca, Caça, Navegação." }
];

export const alphaSpecializations: CatalogItem[] = [
  { name: "Acrobacia", cost: "Esporte", description: "Equilibrar-se, andar sobre cordas e fazer malabarismo." },
  { name: "Alpinismo", cost: "Esporte, Sobrevivência", description: "Escalar montanhas, muros altos e edifícios." },
  { name: "Antropologia", cost: "Ciência", description: "Estudos de culturas humanas e suas origens." },
  { name: "Arqueologia", cost: "Ciência", description: "Estudo de culturas antigas através de vestígios." },
  { name: "Armadilhas", cost: "Crime, Investigação, Máquinas, Sobrevivência", description: "Construir, armar e desarmar armadilhas e explosivos." },
  { name: "Arquearia", cost: "Esporte, Sobrevivência", description: "Habilidade no uso de arco e flecha." },
  { name: "Arremesso", cost: "Esporte", description: "Habilidade em arremessar objetos diversos." },
  { name: "Arrombamento", cost: "Crime, Investigação", description: "Forçar portas e abrir fechaduras trancadas." },
  { name: "Artes Marciais", cost: "Esporte", description: "Conhecimento de sistemas de luta." },
  { name: "Astronomia", cost: "Ciência", description: "Reconhecer estrelas, constelações e ler mapas estelares." },
  { name: "Atuação", cost: "Arte", description: "Simular emoções e representar papéis." },
  { name: "Biologia", cost: "Ciência", description: "Saber tudo sobre plantas e animais." },
  { name: "Boxe", cost: "Esporte", description: "Habilidade em combate com os punhos." },
  { name: "Caça", cost: "Esporte", description: "Habilidade em rastrear e abater presas." },
  { name: "Canto", cost: "Arte", description: "Talento vocal para música." },
  { name: "Ciências Proibidas", cost: "Ciência", description: "Conhecimentos de ocultismo e mistérios." },
  { name: "Cirurgia", cost: "Medicina", description: "Tratar doenças e ferimentos internos." },
  { name: "Código Morse", cost: "Idiomas", description: "Transmitir e receber mensagens em pontos e traços." },
  { name: "Computação", cost: "Máquinas", description: "Operar computadores, internet e quebrar senhas." },
  { name: "Condução", cost: "Máquinas", description: "Dirigir veículos terrestres." },
  { name: "Corrida", cost: "Esporte", description: "Corredor de curta e longa distância." },
  { name: "Criminalística", cost: "Ciência", description: "Estudos de cenas de crime e perícia técnica." },
  { name: "Criptografia", cost: "Crime, Idiomas, Investigação", description: "Criar e decifrar mensagens secretas." },
  { name: "Culinária", cost: "Arte", description: "Habilidade em preparar alimentos." },
  { name: "Dança", cost: "Arte", description: "Expressão artística através do movimento corporal." },
  { name: "Desenho", cost: "Arte", description: "Capacidade de criar ilustrações." },
  { name: "Diagnose", cost: "Medicina", description: "Reconhecer doenças e determinar a cura." },
  { name: "Disfarce", cost: "Crime, Investigação", description: "Parecer-se com outra pessoa." },
  { name: "Doma", cost: "Animais", description: "Domar animais selvagens." },
  { name: "Ecologia", cost: "Ciência", description: "Estudo das relações entre seres vivos e ambiente." },
  { name: "Eletrônica", cost: "Máquinas", description: "Consertar aparelhos eletrônicos." },
  { name: "Engenharia", cost: "Máquinas", description: "Construir máquinas e veículos." },
  { name: "Escultura", cost: "Arte", description: "Criar formas em três dimensões." },
  { name: "Falsificação", cost: "Arte, Crime, Investigação", description: "Criar cópias de documentos e arte." },
  { name: "Fotografia", cost: "Arte", description: "Tirar fotos profissionais." },
  { name: "Furtividade", cost: "Crime, Investigação, Sobrevivência", description: "Mover-se em silêncio e sem ser visto." },
  { name: "Genética", cost: "Ciência", description: "Estudos de DNA e evolução." },
  { name: "Geografia", cost: "Ciência", description: "Fazer mapas e reconhecer lugares." },
  { name: "Hipnose", cost: "Manipulação", description: "Afetar a mente de alguém." },
  { name: "História", cost: "Ciência", description: "Fatos notáveis ocorridos na história." },
  { name: "Instrumentos", cost: "Arte", description: "Tocar instrumentos musicais." },
  { name: "Interrogatório", cost: "Investigação, Manipulação", description: "Obter informações sob pressão." },
  { name: "Intimidação", cost: "Crime, Investigação, Manipulação", description: "Convencer pessoas usando ameaças." },
  { name: "Joalheria", cost: "Arte", description: "Fabricar e consertar joias." },
  { name: "Jogos", cost: "Esporte", description: "Cartas, tabuleiro, e RPGs." },
  { name: "Lábia", cost: "Manipulação", description: "Convencer pessoas usando bajulação." },
  { name: "Leitura Labial", cost: "Idiomas, Investigação", description: "Descobrir o que dizem observando a boca." },
  { name: "Linguagem de Sinais", cost: "Idiomas", description: "Comunicar-se usando gestos." },
  { name: "Literatura", cost: "Ciência", description: "Conhecimento sobre obras literárias." },
  { name: "Mecânica", cost: "Máquinas", description: "Consertar máquinas e veículos." },
  { name: "Mergulho", cost: "Esporte", description: "Uso de equipamento de mergulho." },
  { name: "Metalografia", cost: "Ciência", description: "Estudos e propriedades de metais." },
  { name: "Meteorologia", cost: "Ciência, Sobrevivência", description: "Prever o clima." },
  { name: "Montaria", cost: "Animais", description: "Montar cavalos e outros animais." },
  { name: "Natação", cost: "Esporte", description: "Habilidade em nadar." },
  { name: "Navegação", cost: "Sobrevivência", description: "Dizer onde está e em que direção seguir." },
  { name: "Parkour", cost: "Esporte", description: "Superar obstáculos urbanos com agilidade." },
  { name: "Paraquedismo", cost: "Esporte", description: "Habilidade em saltar com paraquedas." },
  { name: "Pesca", cost: "Sobrevivência", description: "Pegar peixes." },
  { name: "Pilotagem", cost: "Esporte, Máquinas", description: "Pilotar aeronaves e barcos." },
  { name: "Pintura", cost: "Arte", description: "Arte de aplicar pigmentos." },
  { name: "Prestidigitação", cost: "Arte", description: "Truques com pequenos objetos." },
  { name: "Primeiros Socorros", cost: "Medicina", description: "Curativos e estancar sangramentos." },
  { name: "Psiquiatria", cost: "Medicina", description: "Lidar com traumas mentais." },
  { name: "Punga", cost: "Crime", description: "Habilidade em bater carteiras." },
  { name: "Química", cost: "Ciência", description: "Estudos de substâncias." },
  { name: "Rastreio", cost: "Crime, Investigação, Sobrevivência", description: "Seguir pistas e pegadas." },
  { name: "Redação", cost: "Arte", description: "Produzir textos." },
  { name: "Salto", cost: "Esporte", description: "Habilidade em saltar." },
  { name: "Sedução", cost: "Manipulação", description: "Fingir sentimentos românticos." },
  { name: "Tratamento", cost: "Animais", description: "Cuidar de animais." },
  { name: "Treinamento", cost: "Animais", description: "Treinar animais." },
  { name: "Veterinária", cost: "Animais, Medicina", description: "Diagnósticos em animais." }
];

export const alphaRaces: UniqueAdvantageCatalogItem[] = [
  { name: "Humano", type: "Humanos", cost: 0, benefits: "Não possui bônus, sendo o padrão.", drawbacks: "Não possui penalidades." },
  { name: "Anão", type: "Semi-Humanos", cost: 1, benefits: "Infravisão, Resistência à Magia, Testes de Resistência +1, Inimigos (Orcs e Goblinoides).", drawbacks: "Não possui penalidades." },
  { name: "Elfo", type: "Semi-Humanos", cost: 1, benefits: "Habilidade +1, Visão Aguçada, FA+1 com espada e arco, Aptidão para Magia Elemental.", drawbacks: "Não possui penalidades." },
  { name: "Elfo Negro", type: "Semi-Humanos", cost: 2, benefits: "Habilidade +1, Infravisão, Resistência à Magia, Magia Branca ou Negra (grátis).", drawbacks: "Ponto Fraco (luz do dia)." },
  { name: "Gnomo", type: "Semi-Humanos", cost: 2, benefits: "Habilidade +1, Genialidade, Faro Aguçado, Pequenos Desejos (grátis).", drawbacks: "Modelo Especial." },
  { name: "Halfling", type: "Semi-Humanos", cost: 1, benefits: "Habilidade +1, Poder de Fogo +1, Aptidão para Crime.", drawbacks: "Modelo Especial." },
  { name: "Meio-Elfo", type: "Semi-Humanos", cost: 0, benefits: "Visão Aguçada, Aptidão para Artes e Manipulação.", drawbacks: "Não possui penalidades." },
  { name: "Meio-Orc", type: "Semi-Humanos", cost: 0, benefits: "Força +1, Infravisão.", drawbacks: "Má Fama, Proibido comprar Genialidade/Memória Expandida." },
  { name: "Alien", type: "Humanoides", cost: 2, benefits: "Característica +1, Armadura Extra (escolhida), Vantagem Bônus (1 pt).", drawbacks: "Inculto." },
  { name: "Anfíbio", type: "Humanoides", cost: 0, benefits: "Resistência +1, Natação, Radar (na água).", drawbacks: "Ambiente Especial (água), Vulnerabilidade (Fogo)." },
  { name: "Centauro", type: "Humanoides", cost: 1, benefits: "Força +1, Habilidade +1 (para corrida), Combate Táurico.", drawbacks: "Modelo Especial." },
  { name: "Goblin", type: "Humanoides", cost: -1, benefits: "Testes de Resistência +1, Infravisão, Aptidão para Crime.", drawbacks: "Má Fama, Magia custa 3 pts." },
  { name: "Kemono", type: "Humanoides", cost: 1, benefits: "Habilidade +1, Sentidos Especiais (2 à escolha).", drawbacks: "Não possui penalidades." },
  { name: "Meio-Dragão", type: "Humanoides", cost: 4, benefits: "Arcano, Invulnerabilidade (elemento).", drawbacks: "Não possui penalidades." },
  { name: "Minotauro", type: "Humanoides", cost: 0, benefits: "Força +2, Resistência +1, Mente Labiríntica.", drawbacks: "Código de Honra do Combate, Má Fama, Fobia (altura)." },
  { name: "Ogre", type: "Humanoides", cost: 2, benefits: "Força +3, Resistência +3.", drawbacks: "Modelo Especial, Inculto, Má Fama, Monstruoso, etc." },
  { name: "Troglodita", type: "Humanoides", cost: 2, benefits: "Força +1, Armadura +1, Infravisão, Camuflagem, Ataque Pestilento.", drawbacks: "Monstruoso, Vulnerabilidade (Frio)." },
  { name: "Anjo", type: "Youkai", cost: 2, benefits: "Boa Fama, Sentidos Especiais, Invulnerabilidade (Elétrico e Sônico), Aptidão Voo.", drawbacks: "Maldição (banimento), Vulnerabilidade (Fogo)." },
  { name: "Demônio", type: "Youkai", cost: 1, benefits: "Sentidos, Invulnerabilidade (Fogo), Aptidão Voo.", drawbacks: "Má Fama, Maldição, Vulnerabilidade." },
  { name: "Fada", type: "Youkai", cost: 3, benefits: "Habilidade +1, Aparência Inofensiva, Voo, Magia.", drawbacks: "Modelo Especial, Vulnerabilidade (Magia)." },
  { name: "Licantropo", type: "Youkai", cost: 0, benefits: "Força Animal (dobro na forma de fera).", drawbacks: "Forma de Fera (Monstruoso, Modelo Especial, Vulnerabilidade)." },
  { name: "Androide", type: "Construtos", cost: 1, benefits: "Imunidades, Reparos (com Máquinas), Aparência Humana.", drawbacks: "Vulnerável a magias." },
  { name: "Ciborgue", type: "Construtos", cost: 0, benefits: "Imunidades (mínimas), Construto Vivo.", drawbacks: "Cérebro Orgânico (afetado por magias mentais)." },
  { name: "Golem", type: "Construtos", cost: 3, benefits: "Imunidades, Armadura Extra (Magia), Camuflagem.", drawbacks: "Monstruoso." },
  { name: "Mecha", type: "Construtos", cost: 0, benefits: "Imunidades, Aptidão Forma Alternativa, Reparos.", drawbacks: "Modelo Especial." },
  { name: "Robô Positrônico", type: "Construtos", cost: -2, benefits: "Imunidades.", drawbacks: "Código de Honra (Três Leis da Robótica)." },
  { name: "Esqueleto", type: "Mortos-Vivos", cost: 0, benefits: "Imunidades, Infravisão, Energia Negativa, Invulnerabilidade (Frio), Armadura Extra.", drawbacks: "Devoção, Inculto, Monstruoso." },
  { name: "Fantasma", type: "Mortos-Vivos", cost: 3, benefits: "Imunidades, Infravisão, Energia Negativa, Incorpóreo, Imortal.", drawbacks: "Devoção." },
  { name: "Vampiro", type: "Mortos-Vivos", cost: -1, benefits: "Imunidades, Infravisão, Energia Negativa.", drawbacks: "Dependência (sangue/vida), Maldição (sol)." },
  { name: "Zumbi", type: "Mortos-Vivos", cost: -2, benefits: "Imunidades, Infravisão, Energia Negativa.", drawbacks: "Dependência, Lentidão, Inculto, Monstruoso." }
];
